const ClipboardActionTypes = {
   CLEAR_CLIP_LIST: 'CLEAR_CLIP_LIST',
   RESET_CLIP_LIST: 'RESET_CLIP_LIST',
   SET_CLIP_LIST: 'SET_CLIP_LIST',
   ADD_TO_CLIP_LIST: 'ADD_TO_CLIP_LIST',
   TRIM_CLIP_LIST_TO_MAX_SIZE: 'TRIM_CLIP_LIST_TO_MAX_SIZE',
};

export default ClipboardActionTypes;
